name: Android CI/CD Release
on:
  push:
    tags:
      - "v*.*.*"  # 语义化版本号触发（如v1.2.0）
jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建Release
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Build APK with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease
          
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Rename APK
        run: mv "${{ steps.sign_app.outputs.signedReleaseFile }}" HTV_${{ github.ref_name }}.apk
        
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
